---
abstract: 'Mango backend for Minion'
author:
  - 'Andrey Khozov <avkhozov@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.3.0, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Minion-Backend-Mango
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Minion::Backend::Mango:
    file: lib/Minion/Backend/Mango.pm
    version: '0.91'
requires:
  Mango: '1.14'
  Minion: '1.05'
resources:
  bugtracker: https://github.com/avkhozov/Minion-Backend-Mango/issues
  homepage: https://github.com/avkhozov/Minion-Backend-Mango
  repository: git://github.com/avkhozov/Minion-Backend-Mango.git
version: '0.91'
x_authority: cpan:AVKHOZOV
